{% set name = "spectrally" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spectrally-{{ version }}.tar.gz
  sha256: 7943240d7701658907d5fbfd5351cfc8dd041c4c04133557850d0407ea905648

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy <2.0
    - scipy
    - matplotlib-base
    - pandas
    - requests
    - datastock >=0.0.39
    - bsplines2d >=0.0.15

test:
  imports:
    - spectrally
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ToFuProject/spectrally
  summary: A python library for generic spectrum fitting, using datastock
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
